=== Burningstone91/smart-home-setup/home-assistant/custom_components/powercalc/data/model_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "model.json described a light model",
  "type": "object",
  "required": [
    "name",
    "standby_usage",
    "supported_modes",
    "measure_method",
    "measure_device"
  ],
  "properties": {
    "name": {
      "type": "string",
      "description": "The full name"
    },
    "standby_usage": {
      "type": "number",
      "description": "Power draw when the light is turned of. When you are not able to measure set to 0.4"
    },
    "supported_modes": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["lut", "linear", "fixed"]
      },
      "description": "Supported calculation modes"
    },
    "measure_method": {
      "type": "string",
      "enum": ["manual", "script"],
      "description": "How the light was measured"
    },
    "measure_device": {
      "type": "string",
      "description": "Device which was used to measure"
    },
    "measure_description": {
      "type": "string",
      "description": "Add more information about how you measured the light or any remarks"
    },
    "linear_config": {
      "type": "object",
      "description": "Configuration for linear calculation mode",
      "properties": {
        "min_watt": {
          "type": "number"
        },
        "max_watt": {
          "type": "number"
        }
      }
    },
    "fixed_config": {
      "type": "object",
      "description": "Configuration for fixed calculation mode",
      "properties": {
        "watt": {
          "type": "number"
        }
      }
    }
  }
}

=== Burningstone91/smart-home-setup/home-assistant/custom_components/powercalc/data/mueller-licht/ZBT-ColorTemperature/model.json
{
    "name": "tint GU10 Spot 350lm",
    "standby_usage": 0.31,
    "supported_modes": [
        "lut"
    ],
    "measure_method": "script",
    "measure_device": "Shelly Plug S",
    "measure_description": "Measured once with script made by bramstroker using 9 sec pauses and partially verified manual"
}

=== Burningstone91/smart-home-setup/home-assistant/custom_components/powercalc/data/ledvance/Tibea TW Z3/model.json
{
    "name": "Tibea Lamp E27 Tuneable White 2000lm",
    "standby_usage": 0.51,
    "supported_modes": [
        "lut"
    ],
    "measure_method": "script",
    "measure_device": "Shelly Plug S",
    "measure_description": "Measured twice with script made by bramstroker and partially verified manual"
}

=== Burningstone91/smart-home-setup/home-assistant/custom_components/powercalc/data/belkin/F7C033/model.json
{
    "name": "WeMo smart LED bulb",
    "standby_usage": 0.4,
    "supported_modes": [
        "lut"
    ],
    "measure_method": "manual",
    "measure_device": "RRPM02 (Model); 4897037690801 (Barcode); Reduction Revolution Plug-in Power Meter",
    "measure_description": "Was not able to measure the standby usage, the value is assumed"
}

=== Burningstone91/smart-home-setup/home-assistant/custom_components/powercalc/data/signify/LWB004/model.json
{
    "name": "Hue Lux E27 750lm",
    "standby_usage": 0.29,
    "supported_modes": [
        "lut"
    ],
    "measure_method": "manual",
    "measure_device": "Power Recorder; PR10-D (Model); Shenzen Zhurui Technology (Manufacturer)",
    "measure_description": "Bulbs was measured twice at each dim setting (100 points) and mean value was used when there were differences"
}

=== Burningstone91/smart-home-setup/home-assistant/custom_components/powercalc/data/signify/LLC010/model.json
{
    "name": "Hue Iris",
    "standby_usage": 0.40,
    "supported_modes": [
        "lut"
    ],
    "measure_method": "script",
    "measure_device": "TP-Link HS110",
    "measure_description": "Measured with script made by smonesi (steps: bri 50/sat 60/hue 2000) and linearly interpolated to provide more data"
}

=== Burningstone91/smart-home-setup/home-assistant/custom_components/powercalc/data/signify/LWA009/model.json
{
    "name": "Hue White 1600 A67 E27 1600lm",
    "standby_usage": 0.41,
    "supported_modes": [
        "lut"
    ],
    "measure_method": "script",
    "measure_device": "Shelly Plug S",
    "measure_description": "Measured twice with script made by bramstroker using 9 sec pauses and partially verified manual"
}

=== Burningstone91/smart-home-setup/home-assistant/custom_components/powercalc/data/ikea/LED1546G12/model.json
{
    "name": "TRADFRI bulb E27 WS clear 950lm LED1546G12",
    "standby_usage": 0.43,
    "supported_modes": [
        "lut"
    ],
    "measure_method": "script",
    "measure_device": "Shelly Plug S",
    "measure_description": "Measured with script made by bramstroker and partially verified manual"
}

=== Burningstone91/smart-home-setup/home-assistant/custom_components/powercalc/data/sonoff/B02BA60/model.json
{
    "measure_device": "Sonoff DualR3",
    "measure_description": "Took several readings on every 10% of the lamp and did a linear regression to estimate the correct consumptions. Standby usage is assumed",
    "measure_method": "script",
    "name": "Sonoff B02 Light with dimmer and temperature",
    "standby_usage": 0.4,
    "supported_modes": [
        "lut"
    ]
}
