=== Burningstone91/smart-home-setup/home-assistant/custom_components/powercalc/data/model_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "model.json described a light model",
  "type": "object",
  "required": [
    "name",
    "standby_usage",
    "supported_modes",
    "measure_method",
    "measure_device"
  ],
  "properties": {
    "name": {
      "type": "string",
      "description": "The full name"
    },
    "standby_usage": {
      "type": "number",
      "description": "Power draw when the light is turned of. When you are not able to measure set to 0.4"
    },
    "supported_modes": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["lut", "linear", "fixed"]
      },
      "description": "Supported calculation modes"
    },
    "measure_method": {
      "type": "string",
      "enum": ["manual", "script"],
      "description": "How the light was measured"
    },
    "measure_device": {
      "type": "string",
      "description": "Device which was used to measure"
    },
    "measure_description": {
      "type": "string",
      "description": "Add more information about how you measured the light or any remarks"
    },
    "linear_config": {
      "type": "object",
      "description": "Configuration for linear calculation mode",
      "properties": {
        "min_watt": {
          "type": "number"
        },
        "max_watt": {
          "type": "number"
        }
      }
    },
    "fixed_config": {
      "type": "object",
      "description": "Configuration for fixed calculation mode",
      "properties": {
        "watt": {
          "type": "number"
        }
      }
    }
  }
}

=== Burningstone91/smart-home-setup/home-assistant/custom_components/powercalc/data/yeelight/YLDP01YL/model.json
{
    "name": "Yeelight LED 600lm 4000K 8W WiFi",
    "standby_usage": 1.1,
    "supported_modes": [
        "lut"
    ],
    "measure_method": "manual",
    "measure_device": "RRPM02 (Model); 4897037690801 (Barcode); Reduction Revolution Plug-in Power Meter",
    "measure_description": "No comments"
}

=== Burningstone91/smart-home-setup/home-assistant/custom_components/powercalc/data/signify/LTA001/model.json
{
    "name": "Hue White Ambiance E27",
    "standby_usage": 0.29,
    "supported_modes": [
        "lut"
    ],
    "measure_method": "script",
    "measure_device": "TP-Link HS110",
    "measure_description": "Measured with script made by smonesi (steps: bri 30/mired 30) and linearly interpolated to provide more data"
}

=== Burningstone91/smart-home-setup/home-assistant/custom_components/powercalc/data/signify/LCT026/model.json
{
    "name": "Hue Go 2.0",
    "standby_usage": 0.49,
    "measure_method": "script",
    "measure_device": "TP-Link HS110",
    "measure_description": "Measured with measure_v2 script made by smonesi (SAMPLE_COUNT=6, steps: bri 40/sat 40/mired 30/hue 2000) and linearly interpolated to provide more data",
    "supported_modes": [
        "lut"
    ]
}

=== Burningstone91/smart-home-setup/home-assistant/custom_components/powercalc/data/signify/LTW010/model.json
{
    "name": "Hue White Ambiance A60 E27 806lm 9290012001A",
    "standby_usage": 0.39,
    "supported_modes": [
        "lut"
    ],
    "measure_method": "script",
    "measure_device": "Shelly Plug S",
    "measure_description": "Measured with script made by bramstroker and partially verified manual"
}

=== Burningstone91/smart-home-setup/home-assistant/custom_components/powercalc/data/ikea/LED1732G11/model.json
{
    "name": "TRADFRI bulb E27 WS opal 1000lm LED1732G11",
    "standby_usage": 0.26,
    "supported_modes": [
        "lut"
    ],
    "measure_method": "script",
    "measure_device": "Shelly Plug S",
    "measure_description": "Measured with script made by bramstroker and partially verified manual"
}

=== Burningstone91/smart-home-setup/home-assistant/custom_components/powercalc/data/signify/LCT024/model.json
{
    "name": "Hue Play",
    "standby_usage": 0.100,
    "supported_modes": [
        "lut"
    ],
    "measure_method": "script",
    "measure_device": "TP-Link HS110",
    "measure_description": "Measured with script made by smonesi (steps: bri 20/sat 40/mired 30/hue 2000) and linearly interpolated to provide more data"
}

=== Burningstone91/smart-home-setup/home-assistant/custom_components/powercalc/data/ikea/LED1537R6/model.json
{
    "name": "TRADFRI bulb GU10 WS 400lm LED1537R6",
    "standby_usage": 0.44,
    "supported_modes": [
        "lut"
    ],
    "measure_method": "script",
    "measure_device": "Shelly Plug S",
    "measure_description": "Measured once with old version script made by bramstroker using 6 sec pauses and partially verified and fixed manual"
}

=== Burningstone91/smart-home-setup/home-assistant/custom_components/powercalc/data/signify/LWB006/model.json
{
    "name": "Hue White A60 E27 800lm",
    "standby_usage": 0.4,
    "supported_modes": [
        "lut"
    ],
    "measure_method": "manual",
    "measure_device": "RRPM02 (Model); 4897037690801 (Barcode); Reduction Revolution Plug-in Power Meter",
    "measure_description": "Was not able to measure the standby usage, the value is assumed. Two bulbs were measured and the higher reading at each dim setting (0-100) was used"
}
